const SURAHS_LIST = [
  {
    number: 1,
    arabicName: "سورة الفاتحة",
    englishName: "Al-Fatihah",
    slug: "al-fatihah",
  },
  {
    number: 2,
    arabicName: "سورة البقرة",
    englishName: "Al-Baqarah",
    slug: "al-baqarah",
  },
  {
    number: 3,
    arabicName: "سورة آل عمران",
    englishName: "Ali 'Imran",
    slug: "ali-'imran",
  },
  {
    number: 4,
    arabicName: "سورة النساء",
    englishName: "An-Nisa",
    slug: "an-nisa",
  },
  {
    number: 5,
    arabicName: "سورة المائدة",
    englishName: "Al-Ma'numberah",
    slug: "al-ma'numberah",
  },
  {
    number: 6,
    arabicName: "سورة الأنعام",
    englishName: "Al-An'am",
    slug: "al-an'am",
  },
  {
    number: 7,
    arabicName: "سورة الأعراف",
    englishName: "Al-A'raf",
    slug: "al-a'raf",
  },
  {
    number: 8,
    arabicName: "سورة الأنفال",
    englishName: "Al-Anfal",
    slug: "al-anfal",
  },
  {
    number: 9,
    arabicName: "سورة التوبة",
    englishName: "At-Tawbah",
    slug: "at-tawbah",
  },
  {
    number: 10,
    arabicName: "سورة يونس",
    englishName: "Yunus",
    slug: "yunus",
  },
  {
    number: 11,
    arabicName: "سورة هود",
    englishName: "Hud",
    slug: "hud",
  },
  {
    number: 12,
    arabicName: "سورة يوسف",
    englishName: "Yusuf",
    slug: "yusuf",
  },
  {
    number: 13,
    arabicName: "سورة الرعد",
    englishName: "Ar-Ra'd",
    slug: "ar-ra'd",
  },
  {
    number: 14,
    arabicName: "سورة إبراهيم",
    englishName: "Ibrahim",
    slug: "ibrahim",
  },
  {
    number: 15,
    arabicName: "سورة الحجر",
    englishName: "Al-Hijr",
    slug: "al-hijr",
  },
  {
    number: 16,
    arabicName: "سورة النحل",
    englishName: "An-Nahl",
    slug: "an-nahl",
  },
  {
    number: 17,
    arabicName: "سورة الإسراء",
    englishName: "Al-Isra",
    slug: "al-isra",
  },
  {
    number: 18,
    arabicName: "سورة الكهف",
    englishName: "Al-Kahf",
    slug: "al-kahf",
  },
  {
    number: 19,
    arabicName: "سورة مريم",
    englishName: "Maryam",
    slug: "maryam",
  },
  {
    number: 20,
    arabicName: "سورة طه",
    englishName: "Taha",
    slug: "taha",
  },
  {
    number: 21,
    arabicName: "سورة الأنبياء",
    englishName: "Al-Anbya",
    slug: "al-anbya",
  },
  {
    number: 22,
    arabicName: "سورة الحج",
    englishName: "Al-Hajj",
    slug: "al-hajj",
  },
  {
    number: 23,
    arabicName: "سورة المؤمنون",
    englishName: "Al-Mu'minun",
    slug: "al-mu'minun",
  },
  {
    number: 24,
    arabicName: "سورة النور",
    englishName: "An-Nur",
    slug: "an-nur",
  },
  {
    number: 25,
    arabicName: "سورة الفرقان",
    englishName: "Al-Furqan",
    slug: "al-furqan",
  },
  {
    number: 26,
    arabicName: "سورة الشعراء",
    englishName: "Ash-Shu'ara",
    slug: "ash-shu'ara",
  },
  {
    number: 27,
    arabicName: "سورة النمل",
    englishName: "An-Naml",
    slug: "an-naml",
  },
  {
    number: 28,
    arabicName: "سورة القصص",
    englishName: "Al-Qasas",
    slug: "al-qasas",
  },
  {
    number: 29,
    arabicName: "سورة العنكبوت",
    englishName: "Al-'Ankabut",
    slug: "al-'ankabut",
  },
  {
    number: 30,
    arabicName: "سورة الروم",
    englishName: "Ar-Rum",
    slug: "ar-rum",
  },
  {
    number: 31,
    arabicName: "سورة لقمان",
    englishName: "Luqman",
    slug: "luqman",
  },
  {
    number: 32,
    arabicName: "سورة السجدة",
    englishName: "As-Sajdah",
    slug: "as-sajdah",
  },
  {
    number: 33,
    arabicName: "سورة الأحزاب",
    englishName: "Al-Ahzab",
    slug: "al-ahzab",
  },
  {
    number: 34,
    arabicName: "سورة سبأ",
    englishName: "Saba",
    slug: "saba",
  },
  {
    number: 35,
    arabicName: "سورة فاطر",
    englishName: "Fatir",
    slug: "fatir",
  },
  {
    number: 36,
    arabicName: "سورة يس",
    englishName: "Ya-Sin",
    slug: "ya-sin",
  },
  {
    number: 37,
    arabicName: "سورة الصافات",
    englishName: "As-Saffat",
    slug: "as-saffat",
  },
  {
    number: 38,
    arabicName: "سورة ص",
    englishName: "Sad",
    slug: "sad",
  },
  {
    number: 39,
    arabicName: "سورة الزمر",
    englishName: "Az-Zumar",
    slug: "az-zumar",
  },
  {
    number: 40,
    arabicName: "سورة غافر",
    englishName: "Ghafir",
    slug: "ghafir",
  },
  {
    number: 41,
    arabicName: "سورة فصلت",
    englishName: "Fussilat",
    slug: "fussilat",
  },
  {
    number: 42,
    arabicName: "سورة الشورى",
    englishName: "Ash-Shuraa",
    slug: "ash-shuraa",
  },
  {
    number: 43,
    arabicName: "سورة الزخرف",
    englishName: "Az-Zukhruf",
    slug: "az-zukhruf",
  },
  {
    number: 44,
    arabicName: "سورة الدخان",
    englishName: "Ad-Dukhan",
    slug: "ad-dukhan",
  },
  {
    number: 45,
    arabicName: "سورة الجاثية",
    englishName: "Al-Jathiyah",
    slug: "al-jathiyah",
  },
  {
    number: 46,
    arabicName: "سورة الأحقاف",
    englishName: "Al-Ahqaf",
    slug: "al-ahqaf",
  },
  {
    number: 47,
    arabicName: "سورة محمد",
    englishName: "Muhammad",
    slug: "muhammad",
  },
  {
    number: 48,
    arabicName: "سورة الفتح",
    englishName: "Al-Fath",
    slug: "al-fath",
  },
  {
    number: 49,
    arabicName: "سورة الحجرات",
    englishName: "Al-Hujurat",
    slug: "al-hujurat",
  },
  {
    number: 50,
    arabicName: "سورة ق",
    englishName: "Qaf",
    slug: "qaf",
  },
  {
    number: 51,
    arabicName: "سورة الذاريات",
    englishName: "Adh-Dhariyat",
    slug: "adh-dhariyat",
  },
  {
    number: 52,
    arabicName: "سورة الطور",
    englishName: "At-Tur",
    slug: "at-tur",
  },
  {
    number: 53,
    arabicName: "سورة النجم",
    englishName: "An-Najm",
    slug: "an-najm",
  },
  {
    number: 54,
    arabicName: "سورة القمر",
    englishName: "Al-Qamar",
    slug: "al-qamar",
  },
  {
    number: 55,
    arabicName: "سورة الرحمن",
    englishName: "Ar-Rahman",
    slug: "ar-rahman",
  },
  {
    number: 56,
    arabicName: "سورة الواقعة",
    englishName: "Al-Waqi'ah",
    slug: "al-waqi'ah",
  },
  {
    number: 57,
    arabicName: "سورة الحديد",
    englishName: "Al-Hadnumber",
    slug: "al-hadnumber",
  },
  {
    number: 58,
    arabicName: "سورة المجادلة",
    englishName: "Al-Mujadila",
    slug: "al-mujadila",
  },
  {
    number: 59,
    arabicName: "سورة الحشر",
    englishName: "Al-Hashr",
    slug: "al-hashr",
  },
  {
    number: 60,
    arabicName: "سورة الممتحنة",
    englishName: "Al-Mumtahanah",
    slug: "al-mumtahanah",
  },
  {
    number: 61,
    arabicName: "سورة الصف",
    englishName: "As-Saf",
    slug: "as-saf",
  },
  {
    number: 62,
    arabicName: "سورة الجمعة",
    englishName: "Al-Jumu'ah",
    slug: "al-jumu'ah",
  },
  {
    number: 63,
    arabicName: "سورة المنافقون",
    englishName: "Al-Munafiqun",
    slug: "al-munafiqun",
  },
  {
    number: 64,
    arabicName: "سورة التغابن",
    englishName: "At-Taghabun",
    slug: "at-taghabun",
  },
  {
    number: 65,
    arabicName: "سورة الطلاق",
    englishName: "At-Talaq",
    slug: "at-talaq",
  },
  {
    number: 66,
    arabicName: "سورة التحريم",
    englishName: "At-Tahrim",
    slug: "at-tahrim",
  },
  {
    number: 67,
    arabicName: "سورة الملك",
    englishName: "Al-Mulk",
    slug: "al-mulk",
  },
  {
    number: 68,
    arabicName: "سورة القلم",
    englishName: "Al-Qalam",
    slug: "al-qalam",
  },
  {
    number: 69,
    arabicName: "سورة الحاقة",
    englishName: "Al-Haqqah",
    slug: "al-haqqah",
  },
  {
    number: 70,
    arabicName: "سورة المعارج",
    englishName: "Al-Ma'arij",
    slug: "al-ma'arij",
  },
  {
    number: 71,
    arabicName: "سورة نوح",
    englishName: "Nuh",
    slug: "nuh",
  },
  {
    number: 72,
    arabicName: "سورة الجن",
    englishName: "Al-Jinn",
    slug: "al-jinn",
  },
  {
    number: 73,
    arabicName: "سورة المزمل",
    englishName: "Al-Muzzammil",
    slug: "al-muzzammil",
  },
  {
    number: 74,
    arabicName: "سورة المدثر",
    englishName: "Al-Muddaththir",
    slug: "al-muddaththir",
  },
  {
    number: 75,
    arabicName: "سورة القيامة",
    englishName: "Al-Qiyamah",
    slug: "al-qiyamah",
  },
  {
    number: 76,
    arabicName: "سورة الإنسان",
    englishName: "Al-Insan",
    slug: "al-insan",
  },
  {
    number: 77,
    arabicName: "سورة المرسلات",
    englishName: "Al-Mursalat",
    slug: "al-mursalat",
  },
  {
    number: 78,
    arabicName: "سورة النبأ",
    englishName: "An-Naba",
    slug: "an-naba",
  },
  {
    number: 79,
    arabicName: "سورة النازعات",
    englishName: "An-Nazi'at",
    slug: "an-nazi'at",
  },
  {
    number: 80,
    arabicName: "سورة عبس",
    englishName: "'Abasa",
    slug: "'abasa",
  },
  {
    number: 81,
    arabicName: "سورة التكوير",
    englishName: "At-Takwir",
    slug: "at-takwir",
  },
  {
    number: 82,
    arabicName: "سورة الانفطار",
    englishName: "Al-Infitar",
    slug: "al-infitar",
  },
  {
    number: 83,
    arabicName: "سورة المطففين",
    englishName: "Al-Mutaffifin",
    slug: "al-mutaffifin",
  },
  {
    number: 84,
    arabicName: "سورة الانشقاق",
    englishName: "Al-Inshiqaq",
    slug: "al-inshiqaq",
  },
  {
    number: 85,
    arabicName: "سورة البروج",
    englishName: "Al-Buruj",
    slug: "al-buruj",
  },
  {
    number: 86,
    arabicName: "سورة الطارق",
    englishName: "At-Tariq",
    slug: "at-tariq",
  },
  {
    number: 87,
    arabicName: "سورة الأعلى",
    englishName: "Al-A'la",
    slug: "al-a'la",
  },
  {
    number: 88,
    arabicName: "سورة الغاشية",
    englishName: "Al-Ghashiyah",
    slug: "al-ghashiyah",
  },
  {
    number: 89,
    arabicName: "سورة الفجر",
    englishName: "Al-Fajr",
    slug: "al-fajr",
  },
  {
    number: 90,
    arabicName: "سورة البلد",
    englishName: "Al-Balad",
    slug: "al-balad",
  },
  {
    number: 91,
    arabicName: "سورة الشمس",
    englishName: "Ash-Shams",
    slug: "ash-shams",
  },
  {
    number: 92,
    arabicName: "سورة الليل",
    englishName: "Al-Layl",
    slug: "al-layl",
  },
  {
    number: 93,
    arabicName: "سورة الضحى",
    englishName: "Ad-Duhaa",
    slug: "ad-duhaa",
  },
  {
    number: 94,
    arabicName: "سورة الشرح",
    englishName: "Ash-Sharh",
    slug: "ash-sharh",
  },
  {
    number: 95,
    arabicName: "سورة التين",
    englishName: "At-Tin",
    slug: "at-tin",
  },
  {
    number: 96,
    arabicName: "سورة العلق",
    englishName: "Al-'Alaq",
    slug: "al-'alaq",
  },
  {
    number: 97,
    arabicName: "سورة القدر",
    englishName: "Al-Qadr",
    slug: "al-qadr",
  },
  {
    number: 98,
    arabicName: "سورة البينة",
    englishName: "Al-Bayyinah",
    slug: "al-bayyinah",
  },
  {
    number: 99,
    arabicName: "سورة الزلزلة",
    englishName: "Az-Zalzalah",
    slug: "az-zalzalah",
  },
  {
    number: 100,
    arabicName: "سورة العاديات",
    englishName: "Al-'Adiyat",
    slug: "al-'adiyat",
  },
  {
    number: 101,
    arabicName: "سورة القارعة",
    englishName: "Al-Qari'ah",
    slug: "al-qari'ah",
  },
  {
    number: 102,
    arabicName: "سورة التكاثر",
    englishName: "At-Takathur",
    slug: "at-takathur",
  },
  {
    number: 103,
    arabicName: "سورة العصر",
    englishName: "Al-'Asr",
    slug: "al-'asr",
  },
  {
    number: 104,
    arabicName: "سورة الهمزة",
    englishName: "Al-Humazah",
    slug: "al-humazah",
  },
  {
    number: 105,
    arabicName: "سورة الفيل",
    englishName: "Al-Fil",
    slug: "al-fil",
  },
  {
    number: 106,
    arabicName: "سورة قريش",
    englishName: "Quraysh",
    slug: "quraysh",
  },
  {
    number: 107,
    arabicName: "سورة الماعون",
    englishName: "Al-Ma'un",
    slug: "al-ma'un",
  },
  {
    number: 108,
    arabicName: "سورة الكوثر",
    englishName: "Al-Kawthar",
    slug: "al-kawthar",
  },
  {
    number: 109,
    arabicName: "سورة الكافرون",
    englishName: "Al-Kafirun",
    slug: "al-kafirun",
  },
  {
    number: 110,
    arabicName: "سورة النصر",
    englishName: "An-Nasr",
    slug: "an-nasr",
  },
  {
    number: 111,
    arabicName: "سورة المسد",
    englishName: "Al-Masad",
    slug: "al-masad",
  },
  {
    number: 112,
    arabicName: "سورة الإخلاص",
    englishName: "Al-Ikhlas",
    slug: "al-ikhlas",
  },
  {
    number: 113,
    arabicName: "سورة الفلق",
    englishName: "Al-Falaq",
    slug: "al-falaq",
  },
  {
    number: 114,
    arabicName: "سورة الناس",
    englishName: "An-Nas",
    slug: "an-nas",
  },
];
export default SURAHS_LIST;
